#!/usr/bin/env python
from livereload.task import Task
from livereload.compiler import shell

# You may have a different path, e.g. _source/
Task.add('*.rst', shell('make html'))
Task.add('Makefile', shell('make html'))
Task.add('Guardfile', shell('make html'))
Task.add('conf.py', shell('make html'))
